apiVersion: v1
kind: Service
metadata:
  name: kubernet-ci-cd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubernet-ci-cd
  ports:
    - name: http
      port: 80
      targetPort: http

